@echo off
setlocal

set PROJECT=DevMaid.csproj
set RUNTIME=win-x64
set CONFIG=Release

if "%1"=="" goto usage
if "%1"=="nuget" goto nuget
if "%1"=="exe" goto exe
if "%1"=="all" goto all
goto usage

:nuget
echo.
echo ========================================
echo Publishing DevMaid - NuGet Package
echo ========================================
echo.
echo Creating NuGet package...
dotnet publish %PROJECT% -c %CONFIG%
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Publish failed.
    exit /b %ERRORLEVEL%
)
echo.
echo [OK] NuGet package created in bin\%CONFIG%\net10.0\
echo.
echo To install locally:
echo   dotnet tool install --add-source bin\%CONFIG%\net10.0\ devmaid
echo.
goto end

:exe
echo.
echo ========================================
echo Publishing DevMaid - Standalone EXE
echo ========================================
echo.
dotnet publish %PROJECT% ^
    -c %CONFIG% ^
    -r %RUNTIME% ^
    -o .\publish\exe ^
    -p:PublishSingleFile=true ^
    -p:SelfContained=true
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Publish failed.
    exit /b %ERRORLEVEL%
)
echo.
echo [OK] EXE created in .\publish\exe\DevMaid.exe
echo.
goto end

:all
echo.
echo ========================================
echo Publishing DevMaid - All Targets
echo ========================================
echo.
echo [1/2] Creating NuGet package...
dotnet publish %PROJECT% -c %CONFIG%
if %ERRORLEVEL% neq 0 (
    echo [ERROR] NuGet publish failed.
    exit /b %ERRORLEVEL%
)
echo [OK] NuGet package created
echo.
echo [2/2] Creating standalone EXE...
dotnet publish %PROJECT% ^
    -c %CONFIG% ^
    -r %RUNTIME% ^
    -o .\publish\exe ^
    -p:PublishSingleFile=true ^
    -p:SelfContained=true
if %ERRORLEVEL% neq 0 (
    echo [ERROR] EXE publish failed.
    exit /b %ERRORLEVEL%
)
echo [OK] EXE created
echo.
echo ========================================
echo Done!
echo ========================================
echo.
echo Outputs:
echo   - NuGet: bin\%CONFIG%\net10.0\*.nupkg
echo   - EXE:   publish\exe\DevMaid.exe
echo.
goto end

:usage
echo.
echo ========================================
echo DevMaid Publish Script
echo ========================================
echo.
echo Usage: publish.bat [target]
echo.
echo Targets:
echo   nuget  - Create NuGet package for dotnet tool install
echo   exe    - Create standalone EXE for GitHub release
echo   all    - Create both (NuGet + EXE)
echo.
echo Examples:
echo   publish.bat nuget
echo   publish.bat exe
echo   publish.bat all
echo.
echo Note: Version is auto-generated by Nerdbank.GitVersioning
echo.
goto end

:end
endlocal
