param(
    [Parameter(Position = 0)]
    [ValidateSet("nuget", "exe", "all")]
    [string]$Target
)

$ErrorActionPreference = "Stop"

# Project configuration
$PROJECT = "FurLab.CLI/FurLab.CLI.csproj"
$CONFIG = "Release"

# Cross-platform runtime detection
if ($IsWindows) {
    $RUNTIME = "win-x64"
    $EXE_EXT = ".exe"
} elseif ($IsLinux) {
    $RUNTIME = "linux-x64"
    $EXE_EXT = ""
} elseif ($IsMacOS) {
    $RUNTIME = "osx-x64"
    $EXE_EXT = ""
} else {
    # Fallback to Windows if detection fails
    $RUNTIME = "win-x64"
    $EXE_EXT = ".exe"
}

$OUTPUT_DIR = Join-Path "publish" "exe"

function Write-Header {
    param([string]$Message)
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host $Message -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
}

function Build-NuGet {
    Write-Header "Publishing FurLab - NuGet Package"
    
    Write-Host "Creating NuGet package..."
    dotnet publish $PROJECT -c $CONFIG
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] NuGet publish failed." -ForegroundColor Red
        exit 1
    }
    
    $nupkgPath = Join-Path "FurLab.CLI" (Join-Path "bin" (Join-Path $CONFIG "net10.0"))
    Write-Host ""
    Write-Host "[OK] NuGet package created in $nupkgPath\" -ForegroundColor Green
    Write-Host ""
    Write-Host "To install locally:"
    Write-Host "  dotnet tool install --add-source $nupkgPath FurLab"
    Write-Host ""
}

function Build-Exe {
    Write-Header "Publishing FurLab - Standalone Executable"
    
    Write-Host "Creating standalone executable..."
    
    # Ensure output directory exists
    if (-not (Test-Path $OUTPUT_DIR)) {
        New-Item -ItemType Directory -Path $OUTPUT_DIR -Force | Out-Null
    }
    
    dotnet publish $PROJECT `
        -c $CONFIG `
        -r $RUNTIME `
        -o $OUTPUT_DIR `
        -p:PublishSingleFile=true `
        -p:SelfContained=true `
        -p:PublishTrimmed=false
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Executable publish failed." -ForegroundColor Red
        exit 1
    }
    
    # Clean up debug symbols and documentation files
    Get-ChildItem $OUTPUT_DIR -Include *.pdb, *.xml -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
    
    # Rename output to fur.exe (Windows) or fur (Unix)
    $defaultName = "FurLab.CLI$EXE_EXT"
    $newName = "fur$EXE_EXT"
    
    $defaultPath = Join-Path $OUTPUT_DIR $defaultName
    $newPath = Join-Path $OUTPUT_DIR $newName
    
    if (Test-Path $defaultPath) {
        if (Test-Path $newPath) {
            Remove-Item -Path $newPath -Force
        }
        Rename-Item -Path $defaultPath -NewName $newName
    }
    
    # Clean up debug symbols and documentation files
    Get-ChildItem $OUTPUT_DIR -Include *.pdb, *.xml -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
    
    # Rename output to fur.exe (Windows) or fur (Unix)
    $defaultName = "FurLab.CLI$EXE_EXT"
    $newName = "fur$EXE_EXT"
    
    $defaultPath = Join-Path $OUTPUT_DIR $defaultName
    $newPath = Join-Path $OUTPUT_DIR $newName
    
    if (Test-Path $defaultPath) {
        if (Test-Path $newPath) {
            Remove-Item -Path $newPath -Force
        }
        Rename-Item -Path $defaultPath -NewName $newName
    }
    
    if (Test-Path $newPath) {
        Write-Host ""
        Write-Host "[OK] Executable created at $newPath" -ForegroundColor Green
        Write-Host ""
    } else {
        Write-Warning "Expected executable not found at $newPath"
        Write-Host "Contents of $OUTPUT_DIR :"
        Get-ChildItem $OUTPUT_DIR | Format-Table Name, Length
    }
}

function Show-Usage {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "FurLab Publish Script" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Usage: ./publish.ps1 [target]"
    Write-Host ""
    Write-Host "Targets:"
    Write-Host "  nuget  - Create NuGet package for dotnet tool install"
    Write-Host "  exe    - Create standalone executable for GitHub release"
    Write-Host "  all    - Create both (NuGet + executable)"
    Write-Host ""
    Write-Host "Examples:"
    Write-Host "  ./publish.ps1 nuget"
    Write-Host "  ./publish.ps1 exe"
    Write-Host "  ./publish.ps1 all"
    Write-Host ""
    Write-Host "Note: Version is auto-generated by Nerdbank.GitVersioning"
    Write-Host ""
}

# Main execution
if (-not $Target) {
    Show-Usage
    exit 0
}

switch ($Target) {
    "nuget" { Build-NuGet }
    "exe" { Build-Exe }
    "all" {
        Build-NuGet
        Build-Exe
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "Done!" -ForegroundColor Green
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Outputs:"
        Write-Host "  - NuGet:     FurLab.CLI/bin/$CONFIG/net10.0/*.nupkg"
        Write-Host "  - Executable: $OUTPUT_DIR/fur$EXE_EXT"
        Write-Host ""
    }
}
